cv_homepage:
    path:     /
    defaults: { _controller: CvBundle:Default:index }

cv_experience:
    resource: "@CvBundle/Resources/config/routing/experience.yml"
    prefix:   /experience

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yml"